/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-110285-ga3f49168dc-20230416"
#endif /* AVUTIL_FFVERSION_H */
